services:
  postgres:
    image: postgres:17.2-alpine3.21
    restart: unless-stopped
    shm_size: 1gb
    ports:
      - "5445:5432"
    environment:
      POSTGRES_USER: dimipay
      POSTGRES_PASSWORD: dimipay
      POSTGRES_DB: dimipay
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:8.0-M02-alpine3.20
    restart: unless-stopped
    ports:
      - "6336:6379"

volumes:
  postgres-data: